name: Securities Disabled Kernel Build Enforcing

on:
  workflow_dispatch:

jobs:
  Enforcing:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt-get install ccache python3 brotli zip zstd tar lz4 cpio xz-utils pahole libelf-dev python2 -y
        DIR="$(readlink -f .)"
        PARENT_DIR="$(readlink -f "${DIR}/..")"
        git clone https://gitlab.com/tejas101k/clang-r450784d.git/ "$PARENT_DIR/clang-r450784d" --depth=1
    - uses: rui314/setup-mold@v1
    - name: Build
      run: |
        bash buildnoavb.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Enforcing-NoSecurities
        path: kernel_build/langsdorff*
